version: 2

sources:
  - name: portfolio_analyse
    schema: silver_social_media_dbt
    tables:
      - name: t_reddit_posts
        description: "This table contains Reddit posts data."
        columns:
          - name: id
            description: "The unique identifier for each post."
          - name: author
            description: "The author of the post."
          # Weitere Spaltenbeschreibungen hinzufügen
      - name: t_reddit_comments
        description: "This table contains Reddit comments data."
        columns:
          - name: id
            description: "The unique identifier for each comment."
          - name: author
            description: "The author of the comment."
          # Weitere Spaltenbeschreibungen hinzufügen

models:
  - name: v_reddit_posts_comments
    description: "This model combines Reddit posts and comments."
    columns:
      - name: posts_id
        description: "The unique identifier for each post."
      - name: comments_id
        description: "The unique identifier for each comment."
      # Weitere Spaltenbeschreibungen hinzufügen
    tests:
      - unique:
          column_name: posts_id
      - not_null:
          column_name: posts_id
      - unique:
          column_name: comments_id
      - not_null:
          column_name: comments_id
